### ISSUE TITLE
Bug when student requests an invitation

### ISSUE THREAD

**Issue by vvandenschrieck** [TLCA-project/tlca-backend#4]
Context :
- Connected user with student account
- On an invite-only course page, push on "request invitation button"

Output :

- Error popup : error.Cannot return null for non-nullable field Registration.datetime.

**Comment by combefis** [comment]
Thank you for reporting it @vvandenschrieck!

The bug has been identified and was due to a refactoring of the Registration type definition. The 'date' field has been renamed to 'datetime' but no resolver had been defined at that time.

It is solved by commit 929e4d69d1872ffbc2c4cf76580f0430d347c69f which has been merged in the develop and main branches (resulting in a new release v1.02 on main branch)
